# Generated by Django 5.0.4 on 2024-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='tasks_in_variant',
            field=models.IntegerField(default=2, verbose_name='Количество заданий в варианте'),
            preserve_default=False,
        ),
    ]
