# Generated by Django 5.0.4 on 2024-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0002_olympiad_tasks_in_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_description',
            field=models.ImageField(blank=True, upload_to='media/description', verbose_name='Фото описания'),
        ),
        migrations.AddField(
            model_name='task',
            name='image_solution',
            field=models.ImageField(blank=True, upload_to='media/solution', verbose_name='Фото решения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Условие задачи'),
        ),
    ]
