# Generated by Django 5.0.4 on 2024-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0003_task_image_description_task_image_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_description',
            field=models.ImageField(blank=True, upload_to='description', verbose_name='Фото описания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_solution',
            field=models.ImageField(blank=True, upload_to='solution', verbose_name='Фото решения'),
        ),
    ]
