NOT_SELECTED = "📕"
SELECTED = "📗"

CALLBACK_CREATE_GRADE = "GRADE_CREATE_{pk}"
CALLBACK_DELETE_GRADE = "GRADE_DELETE_{pk}"

CALLBACK_START_SOLUTION = "START_SOLUTION"
CALLBACK_OPEN_FAVOURITE_TASKS = "FAVOURITE_TASKS"