# Generated by Django 5.0.4 on 2024-05-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Любимая задача',
                'verbose_name_plural': 'Любимые задачи',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('NA', '_'), ('PC', 'Решается'), ('WA', 'Неправильно'), ('OK', 'Правильно')], default='NA', max_length=15, verbose_name='Состояние задачи')),
            ],
            options={
                'verbose_name': 'Попытка пользователя',
                'verbose_name_plural': 'Попытки пользователя',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionUserGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_user_to_grade', to='minor.grade', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс пользователя',
                'verbose_name_plural': 'Классы пользователя',
                'ordering': ['pk'],
            },
        ),
    ]
