# Generated by Django 5.0.4 on 2024-05-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('minor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionusergrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_user_to_grade', to='users.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='favouritetasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_tasks', to='minor.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='favouritetasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_favourite_tasks', to='users.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tries', to='minor.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tries', to='users.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='connectionusergrade',
            unique_together={('user', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='favouritetasks',
            unique_together={('user', 'task')},
        ),
    ]
