# Generated by Django 5.0.4 on 2024-06-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('minor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedUserTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='using_tip', to='minor.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='using_tip', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задания с подсказкой пользователя',
                'verbose_name_plural': 'Задания с подсказкой пользователя',
                'ordering': ['pk'],
            },
        ),
    ]
