# Generated by Django 5.0.4 on 2024-06-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_usedusertip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedusertip',
            options={'ordering': ['pk'], 'verbose_name': 'Задание с подсказкой', 'verbose_name_plural': 'Задания с подсказкой'},
        ),
    ]
