# Generated by Django 5.0.4 on 2024-06-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_usertaskenroll'),
        ('minor', '0003_task_image_description_task_image_solution_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('NA', '_'), ('WA', 'Неправильно'), ('OK', 'Правильно')], default='NA', max_length=15, verbose_name='Состояние задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tries', to='minor.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tries', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка пользователя',
                'verbose_name_plural': 'Попытки пользователя',
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
