from bot.handlers.begin.manage_data import CALLBACK_START_SOLVING

CALLBACK_SELECT_SUBJECT = "SUBJECT_{pk}"
CALLBACK_SELECT_OLYMPIAD = "OLYMPIAD_{pk}"

CALLBACK_TASKS_METOD = "METOD"

CALLBACK_YEAR_SHIFT_RIGHT = "YEAR_RIGHT_{from_}"
CALLBACK_YEAR_SHIFT_LEFT = "YEAR_LEFT_{from_}"