CALLBACK_CREATE_FAVOURITE_TASK = "CREATE_FAVOURITE_TASK_{pk}"
CALLBACK_DELETE_FAVOURITE_TASK = "DELETE_FAVOURITE_TASK_{pk}"

CALLBACK_ADD_TIP = "UNLOCK_TIP_{pk}"
CALLBACK_SHOW_SOLUTION = "SOLUTION_FOR_TASK_{pk}"