CALLBACK_CREATE_FAVOURITE_TASK = "CREATE_FAVOURITE_TASK"
CALLBACK_DELETE_FAVOURITE_TASK = "DELETE_FAVOURITE_TASK"

CALLBACK_REDIRECT_TASK_WITH_UNNNORMAL_ANSWER_TO_SOLUTION = "REDIRECT_TASK"
CALLBACK_ADD_TIP = "UNLOCK_TIP"
CALLBACK_SHOW_SOLUTION = "SOLUTION"

CALLBACK_ADD_TRUE_USER_TRY = "ADD_TRUE_ANSWER"
CALLBACK_ADD_WRONG_USER_TRY = "ADD_WRONG_ANSWER"